### ISSUE TITLE
Asset post processor runs on every asset in a giant project just to set theme to null

### ISSUE THREAD

**Issue by ecuzzillo** [needle-tools/needle-console#19]
private class AssetProcessor : AssetPostprocessor
		{
			private void OnPreprocessAsset()
			{
				ThemeNames = null;
				Themes = null;
			}
		}

This slows down asset importing, and I can't imagine it's important to do it again for every one of the thousands of assets in the 200GB+ project.

**Comment by marwie** [comment]
Hi good point, thanks for the report

**Comment by marwie** [comment]
@ecuzzillo any info?

**Comment by ecuzzillo** [comment]
Sorry! Yes, that fixed it, thank you!
