### ISSUE TITLE
Unity 2021.3.24f1 : Script Error

### ISSUE THREAD

**Issue by clandais** [needle-tools/needle-console#21]
Upon upgrading to Unity 2021.3.24f1, the Unity Console complains with:

`Library\PackageCache\com.needle.console@2.3.15\Editor\CustomConsole\ConsoleList.cs(545,45): error CS7036: There is no argument given that corresponds to the required formal parameter 'shouldStripCallstack' of 'ConsoleWindow.StacktraceWithHyperlinks(string, int, bool, ConsoleWindow.Mode)'
`
Looks like it goes into the `#else` of `#if UNITY_2022_2_OR_NEWER`
```csharp
#if UNITY_CONSOLE_STACKTRACE_TWO_PARAMETERS
    #if UNITY_2022_2_OR_NEWER
      // mode doesn't matter when shouldStripCallstack is false
      var stackWithHyperlinks = ConsoleWindow.StacktraceWithHyperlinks(message, 0, false, ConsoleWindow.Mode.Log);
    #else
      var stackWithHyperlinks = ConsoleWindow.StacktraceWithHyperlinks(message, 0);
    #endif
  #else
  var stackWithHyperlinks = ConsoleWindow.StacktraceWithHyperlinks(message);
#endif
```

**Comment by marwie** [comment]
Hi, which console package version are you currently using?

**Comment by clandais** [comment]
> Hi, which console package version are you currently using?  

The one in Open UPM ( 2.3.15 )

**Comment by marwie** [comment]
Ok, thanks for bringing it up. If you can a PR would be greatly appreciated 😊

**Comment by clandais** [comment]
I'll ask Chat GPT how to do that :')
