### ISSUE TITLE
[Support Unity Logging]

### ISSUE THREAD

**Issue by aprius** [needle-tools/needle-console#24]
The Logging package is a versatile and highly configurable structured asynchronous logging solution. In addition to what you would expect from a traditional logging package (level, timestamp, stacktrace), it contains various ways to stream and record the logs such as StdOut, text or JSON files, DebugLog, and your own custom implementation. You can also individually or collectively configure these logs.

https://docs.unity3d.com/Packages/com.unity.logging@1.0/manual/index.html

It can be used to replace the default Debug.Log.

**Comment by yenmoc** [comment]
I thought that apart from the extended logging to the file it would still work like the regular log existing in the editor?.

Because I still see the log on console and not highlighted by needle console. 

If it was my mistake, I sincerely apologize

**Comment by marwie** [comment]
The Unity logs are already logged to a file by default
![image](https://github.com/needle-tools/needle-console/assets/5083203/8cfdad75-95f4-4074-874d-6822f70522c7)

What do you mean by `Because I still see the log on console and not highlighted by needle console.` ?

**Comment by yenmoc** [comment]
Log.Info(string message);

stack trace in console not affect by hight light setting of needle console it still same normal log

**Comment by marwie** [comment]
What is `Log.info` ? Which namespace - is that the Logging package?

Can you show a screenshot?

**Comment by yenmoc** [comment]
Well it's from the `Logging` package. sorry I don't have the test snapshot from `Log.Info` right now, I'll try again and send it to you later

**Comment by marwie** [comment]
Ah I guess I'm starting to understand what you're asking :)
